sbatch slurm_jobs/slurm_psr_model_noise_batch_1245.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1246.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1247.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1248.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1249.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1250.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1251.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1252.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1253.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1254.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1255.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1256.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1257.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1258.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1259.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1260.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1261.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1262.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1263.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1264.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1265.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1266.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1267.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1268.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1269.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1270.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1271.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1272.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1273.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1274.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1275.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1276.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1277.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1278.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1279.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1280.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1281.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1282.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1283.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1284.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1285.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1286.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1287.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1288.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1289.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1290.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1291.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1292.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1293.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1294.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1295.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1296.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1297.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1298.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1299.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1300.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1301.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1302.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1303.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1304.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1305.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1306.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1307.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1308.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1309.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1310.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1311.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1312.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1313.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1314.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1315.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1316.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1317.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1318.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1319.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1320.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1321.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1322.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1323.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1324.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1325.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1326.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1327.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1328.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1329.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1330.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1331.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1332.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1333.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1334.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1335.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1336.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1337.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1338.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1339.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1340.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1341.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1342.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1343.sh & 
sbatch slurm_jobs/slurm_psr_model_noise_batch_1344.sh & 
