name = "StateSpacePTA"
uuid = "4ba01001-7b96-4067-852f-8e57af2ea203"
authors = ["Tom Kimpson <tomkimpson@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
